# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "factorymasters", :id => false, :force => true do |t|
    t.column "FactoryId", :integer, :null => false
    t.column "FactoryName", :string, :default => "", :null => false
  end

  create_table "factoryoutputs", :force => true do |t|
    t.column "FactoryId", :integer, :default => 0, :null => false
    t.column "DatePro", :date, :null => false
    t.column "Quantity", :float, :default => 0.0, :null => false
  end

  add_index "factoryoutputs", ["FactoryId"], :name => "fk_factoryoutputs_factorymasters"

end
